### PR TITLE
added catch by fleet diagnostics

### PR DESCRIPTION
**Pull request by jcaracappa1**
- magnitude of catch
- center of gravity of catch

### CODE REVIEW

**Comment by andybeet** [comment]
@jcaracappa1 At first glance we are using different argument names and output names for the same things across functions. eg. fgs (used in other diagnostics function) vs fgs.file (in this new function) vs groups.file (output of get_atl_parmamfiles). Same thing with fishery/catch files. Not something i am suggesting we should fix now but might be worth doing/addressing in the future

**Comment by jcaracappa1** [comment]
Which argument names look unchanged?

**Comment by jcaracappa1** [comment]
@andybeet Do you think we should rename anything before merging?

**Comment by jcaracappa1** [comment]
@andybeet That should be fixed now

**Comment by andybeet** [comment]
i dont think this will run. still left over names in code. But i dont have a `catch.ref` object to test it

**Comment by jcaracappa1** [comment]
@andybeet Good catch. updated.

**Review by andybeet — APPROVED** [review]

**Pull request merged**
